services:

  spark-master:
    image: apache/spark:4.1.3-scala2.13-java17-python3-ubuntu

    container_name: retailpulse-spark-master

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master
      - --host
      - spark-master
      - --port
      - "7077"
      - --webui-port
      - "8080"

    ports:
      - "7077:7077"
      - "8080:8080"

    restart: unless-stopped

    networks:
      - retailpulse-network


  spark-worker:
    image: apache/spark:4.1.3-scala2.13-java17-python3-ubuntu

    container_name: retailpulse-spark-worker

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077
      - --webui-port
      - "8081"
      - --cores
      - "2"
      - --memory
      - "2G"

    ports:
      - "8081:8081"

    depends_on:
      - spark-master

    restart: unless-stopped

    networks:
      - retailpulse-network