services:

  spark-master:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile

    container_name: retailpulse-spark-master

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master
      - --host
      - spark-master
      - --port
      - "7077"
      - --webui-port
      - "8080"

    ports:
      - "7077:7077"
      - "8080:8080"

    restart: unless-stopped

    networks:
      - retailpulse-network

    volumes:
      - ./services/spark-processor:/opt/retailpulse/spark-processor
    environment:
      # Explicitly use Python 3 for PySpark
      PYSPARK_PYTHON: python3
      PYSPARK_DRIVER_PYTHON: python3
  spark-worker:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile

    container_name: retailpulse-spark-worker

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077
      - --webui-port
      - "8081"
      - --cores
      - "2"
      - --memory
      - "2G"

    ports:
      - "8081:8081"

    depends_on:
      - spark-master

    restart: unless-stopped

    networks:
      - retailpulse-network
    volumes:
      - ./services/spark-processor:/opt/retailpulse/spark-processor
    environment:
      # Explicitly use Python 3 for PySpark
      PYSPARK_PYTHON: python3
      PYSPARK_DRIVER_PYTHON: python3